
-- 002_reference - the core store, as a real schema.
--
-- GENERATED by scripts/gen_seed_sql.py from app/coremock/store.py. Do not
-- edit by hand: the fixtures in Python are the source of truth, and a hand
-- edit here would drift from what the offline tests assert.
--
-- Redshift notes that shaped this:
--   * PRIMARY KEY and UNIQUE are recorded but NOT enforced. Uniqueness is
--     the application's job - see mcb.write_ledger and the MERGE pattern.
--   * DISTSTYLE ALL suits every table here; the whole dataset is kilobytes.
--   * No ON CONFLICT. Seeding therefore DELETEs then INSERTs, which also
--     makes this migration safe to re-run.

CREATE SCHEMA IF NOT EXISTS mcb;

CREATE TABLE IF NOT EXISTS mcb.customers (
    user_id      VARCHAR(64)  NOT NULL,
    customer_id  VARCHAR(32)  NOT NULL,
    name         VARCHAR(128),
    city         VARCHAR(64),
    pincode      VARCHAR(12),
    kyc_status   VARCHAR(24)
) DISTSTYLE ALL SORTKEY (user_id);

CREATE TABLE IF NOT EXISTS mcb.producers (
    user_id            VARCHAR(64) NOT NULL,
    producer_id        VARCHAR(32) NOT NULL,
    name               VARCHAR(128),
    licence            VARCHAR(64),
    branch             VARCHAR(64),
    licence_valid_to   DATE
) DISTSTYLE ALL SORTKEY (user_id);

CREATE TABLE IF NOT EXISTS mcb.policies (
    policy_id     VARCHAR(32) NOT NULL,
    lob           VARCHAR(16) NOT NULL,
    product_id    VARCHAR(16),
    product_name  VARCHAR(128),
    customer_id   VARCHAR(32) NOT NULL,
    status        VARCHAR(24),
    start_date    DATE,
    end_date      DATE,
    renewed_to    DATE,
    sum_insured   BIGINT,
    idv           BIGINT,
    ncb_pct       INTEGER
) DISTSTYLE ALL SORTKEY (customer_id, lob);

CREATE TABLE IF NOT EXISTS mcb.policy_members (
    policy_id  VARCHAR(32) NOT NULL,
    member_id  VARCHAR(16) NOT NULL,
    name       VARCHAR(128),
    age        INTEGER,
    relation   VARCHAR(32)
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.policy_vehicles (
    policy_id     VARCHAR(32) NOT NULL,
    registration  VARCHAR(24),
    make          VARCHAR(48),
    model         VARCHAR(48),
    variant       VARCHAR(48),
    year          INTEGER,
    fuel          VARCHAR(24),
    rto           VARCHAR(48)
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.policy_documents (
    policy_id  VARCHAR(32) NOT NULL,
    document   VARCHAR(64) NOT NULL
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.vehicles (
    registration    VARCHAR(24) NOT NULL,
    make            VARCHAR(48),
    model           VARCHAR(48),
    variant         VARCHAR(48),
    year            INTEGER,
    fuel            VARCHAR(24),
    cc              INTEGER,
    vehicle_class   VARCHAR(32),
    rto             VARCHAR(48),
    prior_insurer   VARCHAR(48),
    prior_ncb_pct   INTEGER,
    prior_expiry    DATE
) DISTSTYLE ALL SORTKEY (registration);

CREATE TABLE IF NOT EXISTS mcb.network (
    kind      VARCHAR(16) NOT NULL,   -- hospital | garage
    name      VARCHAR(128) NOT NULL,
    city      VARCHAR(64),
    pincode   VARCHAR(12),
    cashless  BOOLEAN,
    km        DECIMAL(6,2)
) DISTSTYLE ALL SORTKEY (kind, pincode);

CREATE TABLE IF NOT EXISTS mcb.network_specialties (
    name       VARCHAR(128) NOT NULL,
    specialty  VARCHAR(48)  NOT NULL
) DISTSTYLE ALL SORTKEY (name);

-- Transactional state. Typed envelope, JSON body - see the module docstring
-- for why these are not fully columnar.
CREATE TABLE IF NOT EXISTS mcb.quotes (
    quote_id     VARCHAR(48) NOT NULL,
    lob          VARCHAR(16),
    customer_id  VARCHAR(32),
    created_at   TIMESTAMP DEFAULT SYSDATE,
    body         VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (quote_id);

CREATE TABLE IF NOT EXISTS mcb.applications (
    application_id  VARCHAR(48) NOT NULL,
    quote_id        VARCHAR(48),
    customer_id     VARCHAR(32),
    lob             VARCHAR(16),
    status          VARCHAR(32),
    updated_at      TIMESTAMP DEFAULT SYSDATE,
    body            VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (application_id);

CREATE TABLE IF NOT EXISTS mcb.claims (
    claim_id     VARCHAR(48) NOT NULL,
    policy_id    VARCHAR(32),
    lob          VARCHAR(16),
    status       VARCHAR(32),
    updated_at   TIMESTAMP DEFAULT SYSDATE,
    body         VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (claim_id);

-- ---- seed ----
DELETE FROM mcb.customers;
DELETE FROM mcb.producers;
DELETE FROM mcb.policies;
DELETE FROM mcb.policy_members;
DELETE FROM mcb.policy_vehicles;
DELETE FROM mcb.policy_documents;
DELETE FROM mcb.vehicles;
DELETE FROM mcb.network;
DELETE FROM mcb.network_specialties;
INSERT INTO mcb.customers (user_id, customer_id, name, city, pincode, kyc_status) VALUES ('919820000009', 'C-10001', 'Priya Sharma', 'Pune', '411038', 'verified');
INSERT INTO mcb.customers (user_id, customer_id, name, city, pincode, kyc_status) VALUES ('919820000002', 'C-10002', 'Rohit Verma', 'Mumbai', '400058', 'pending');
INSERT INTO mcb.customers (user_id, customer_id, name, city, pincode, kyc_status) VALUES ('919820000003', 'C-10003', 'Anita Desai', 'Bengaluru', '560095', 'not_started');
INSERT INTO mcb.producers (user_id, producer_id, name, licence, branch, licence_valid_to) VALUES ('919820000001', 'P-2201', 'Rakesh Nair', 'POSP/2024/MH/88213', 'Pune West', '2027-03-31');
INSERT INTO mcb.producers (user_id, producer_id, name, licence, branch, licence_valid_to) VALUES ('agent-demo', 'P-2202', 'Demo Producer', 'POSP/2024/MH/00000', 'Demo', '2027-03-31');
INSERT INTO mcb.policies (policy_id, lob, product_id, product_name, customer_id, status, start_date, end_date, renewed_to, sum_insured, idv, ncb_pct) VALUES ('PHS-4471902', 'health', 'PHS', 'Protec Health Secure', 'C-10001', 'in_force', '2025-06-14', '2026-06-13', '2026-06-14', 1000000, NULL, NULL);
INSERT INTO mcb.policy_members (policy_id, member_id, name, age, relation) VALUES ('PHS-4471902', 'M1', 'Priya Sharma', 34, 'self');
INSERT INTO mcb.policy_members (policy_id, member_id, name, age, relation) VALUES ('PHS-4471902', 'M2', 'Arjun Sharma', 37, 'spouse');
INSERT INTO mcb.policy_members (policy_id, member_id, name, age, relation) VALUES ('PHS-4471902', 'M3', 'Meera Sharma', 62, 'mother');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PHS-4471902', 'policy_schedule');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PHS-4471902', 'e_card');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PHS-4471902', 'premium_receipt');
INSERT INTO mcb.policies (policy_id, lob, product_id, product_name, customer_id, status, start_date, end_date, renewed_to, sum_insured, idv, ncb_pct) VALUES ('PMS-8830145', 'motor', 'PMS', 'Protec Motor Shield', 'C-10001', 'in_force', '2026-01-08', '2027-01-07', NULL, NULL, 480000, 35);
INSERT INTO mcb.policy_vehicles (policy_id, registration, make, model, variant, year, fuel, rto) VALUES ('PMS-8830145', 'MH12AB1234', 'Maruti', 'Baleno', 'Zeta', 2021, 'Petrol', 'MH12 Pune');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PMS-8830145', 'policy_schedule');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PMS-8830145', 'premium_receipt');
INSERT INTO mcb.policies (policy_id, lob, product_id, product_name, customer_id, status, start_date, end_date, renewed_to, sum_insured, idv, ncb_pct) VALUES ('PHSR-2210033', 'health', 'PHSR', 'Protec Health Senior Care', 'C-10002', 'in_force', '2026-06-01', '2027-05-31', NULL, 500000, NULL, NULL);
INSERT INTO mcb.policy_members (policy_id, member_id, name, age, relation) VALUES ('PHSR-2210033', 'M1', 'Rohit Verma', 66, 'self');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PHSR-2210033', 'policy_schedule');
INSERT INTO mcb.policy_documents (policy_id, document) VALUES ('PHSR-2210033', 'e_card');
INSERT INTO mcb.vehicles (registration, make, model, variant, year, fuel, cc, vehicle_class, rto, prior_insurer, prior_ncb_pct, prior_expiry) VALUES ('MH12AB1234', 'Maruti', 'Baleno', 'Zeta', 2021, 'Petrol', 1197, 'private_car', 'MH12 Pune', 'Protec', 35, '2027-01-07');
INSERT INTO mcb.vehicles (registration, make, model, variant, year, fuel, cc, vehicle_class, rto, prior_insurer, prior_ncb_pct, prior_expiry) VALUES ('KA05MN7788', 'Hyundai', 'i20', 'Sportz', 2019, 'Petrol', 1197, 'private_car', 'KA05 Bengaluru', 'Other', 20, '2026-08-02');
INSERT INTO mcb.vehicles (registration, make, model, variant, year, fuel, cc, vehicle_class, rto, prior_insurer, prior_ncb_pct, prior_expiry) VALUES ('MH14XY9021', 'Honda', 'Activa', '6G', 2020, 'Petrol', 109, 'two_wheeler', 'MH14 Pimpri', 'Other', 25, '2026-05-19');
INSERT INTO mcb.vehicles (registration, make, model, variant, year, fuel, cc, vehicle_class, rto, prior_insurer, prior_ncb_pct, prior_expiry) VALUES ('DL8CAF4412', 'Toyota', 'Innova Crysta', 'GX', 2014, 'Diesel', 2393, 'private_car', 'DL8C Delhi', 'Other', 0, '2026-04-30');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('hospital', 'Sahyadri Super Speciality', 'Pune', '411004', TRUE, 2.4);
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Sahyadri Super Speciality', 'orthopaedics');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Sahyadri Super Speciality', 'cardiology');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('hospital', 'Ruby Hall Clinic', 'Pune', '411001', TRUE, 4.1);
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Ruby Hall Clinic', 'orthopaedics');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Ruby Hall Clinic', 'oncology');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('hospital', 'Jehangir Hospital', 'Pune', '411001', TRUE, 4.8);
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Jehangir Hospital', 'general');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Jehangir Hospital', 'paediatrics');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('hospital', 'Kokilaben Dhirubhai Ambani', 'Mumbai', '400053', TRUE, 3.2);
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Kokilaben Dhirubhai Ambani', 'cardiology');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Kokilaben Dhirubhai Ambani', 'oncology');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Kokilaben Dhirubhai Ambani', 'neurology');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('hospital', 'Manipal Hospital Sarjapur', 'Bengaluru', '560035', TRUE, 5.6);
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Manipal Hospital Sarjapur', 'general');
INSERT INTO mcb.network_specialties (name, specialty) VALUES ('Manipal Hospital Sarjapur', 'orthopaedics');
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('garage', 'AutoCare Kothrud', 'Pune', '411038', TRUE, 1.9);
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('garage', 'Speedworks Baner', 'Pune', '411045', TRUE, 6.3);
INSERT INTO mcb.network (kind, name, city, pincode, cashless, km) VALUES ('garage', 'Sai Motors Andheri', 'Mumbai', '400053', TRUE, 2.1);
