"""Where the core record data actually lives.

`store.py` keeps every behaviour that makes the core interesting - latency,
rate limits, gates, idempotency, the refusal to issue a policy whose gates are
not all cleared. None of that changes when the rows move to Redshift. What
changes is only where a row is read from, so that is the one thing behind an
interface.

Two backends, chosen by configuration:

* **memory** - the dicts in `store.py`. What the 164 offline tests run
  against, and what `NO_AWS=1` gives you with no credentials at all.
* **redshift** - the same rows, in the schema generated by
  `scripts/gen_seed_sql.py`.

The seam is deliberately narrow. A backend answers questions about records;
it does not know what a gate is, or that a motor policy cannot be issued
before an inspection passes. Push that logic down here and it would have to
exist twice, and the two copies would disagree.

**psycopg2, not psycopg3.** Redshift reports its client encoding as `UNICODE`,
which Python has no codec for; psycopg2 maps it to `utf_8` and psycopg3 does
not. Found by a Lambda that connected fine and then failed on its first query.
"""
from __future__ import annotations

import json
import logging
import threading

from app.config import settings

log = logging.getLogger("mcb.core.backend")

_LOCAL = threading.local()


def using_redshift() -> bool:
    cfg = settings()
    import os

    if os.getenv("NO_AWS") == "1" or cfg.no_aws:
        return False
    return bool(cfg.redshift_host)


# ---------------------------------------------------------------------------
# connection
# ---------------------------------------------------------------------------
def _conn():
    """One connection per thread, reopened if the server dropped it.

    Redshift Serverless pauses when idle and a pooled connection does not
    survive that, so a dead connection is replaced rather than raised - the
    first query after an idle period should wake the warehouse, not fail.
    """
    c = getattr(_LOCAL, "conn", None)
    if c is not None:
        try:
            if not c.closed:
                return c
        except Exception:                                    # noqa: BLE001
            pass
    import psycopg2

    cfg = settings()
    c = psycopg2.connect(
        host=cfg.redshift_host, port=cfg.redshift_port,
        dbname=cfg.redshift_db, user=cfg.redshift_user,
        password=cfg.redshift_password, connect_timeout=30)
    c.autocommit = True
    _LOCAL.conn = c
    return c


def _rows(sql: str, args: tuple = ()) -> list[dict]:
    with _conn().cursor() as cur:
        cur.execute(sql, args)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r)) for r in cur.fetchall()]


def _exec(sql: str, args: tuple = ()) -> None:
    with _conn().cursor() as cur:
        cur.execute(sql, args)


def _one(sql: str, args: tuple = ()) -> dict | None:
    rows = _rows(sql, args)
    return rows[0] if rows else None


def _clean(d: dict) -> dict:
    """Drop NULL columns so a Redshift row reads like the dict it replaced.

    A motor policy has no `sum_insured` and a health policy has no `idv`. In
    the fixtures those keys are simply absent; in SQL they are NULL. Leaving
    them in would make `"sum_insured" in policy` true for a motor policy,
    which is the kind of difference that only shows up in an answer.
    """
    return {k: v for k, v in d.items() if v is not None}


# ---------------------------------------------------------------------------
# reads
# ---------------------------------------------------------------------------
def customer(user_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._CUSTOMERS.get(user_id)
    row = _one("SELECT customer_id, name, city, pincode, kyc_status "
               "FROM mcb.customers WHERE user_id = %s", (user_id,))
    if not row:
        return None
    row = _clean(row)
    row["policies"] = [r["policy_id"] for r in _rows(
        "SELECT policy_id FROM mcb.policies WHERE customer_id = %s "
        "ORDER BY policy_id", (row["customer_id"],))]
    return row


def producer(user_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._PRODUCERS.get(user_id)
    row = _one("SELECT producer_id, name, licence, branch, "
               "TO_CHAR(licence_valid_to, 'YYYY-MM-DD') AS licence_valid_to "
               "FROM mcb.producers WHERE user_id = %s", (user_id,))
    return _clean(row) if row else None


def _hydrate_policy(row: dict) -> dict:
    p = _clean(row)
    pid = p["policy_id"]
    members = _rows("SELECT member_id, name, age, relation "
                    "FROM mcb.policy_members WHERE policy_id = %s "
                    "ORDER BY member_id", (pid,))
    if members:
        p["members"] = [_clean(m) for m in members]
    veh = _one("SELECT registration, make, model, variant, year, fuel, rto "
               "FROM mcb.policy_vehicles WHERE policy_id = %s", (pid,))
    if veh:
        p["vehicle"] = _clean(veh)
    docs = _rows("SELECT document FROM mcb.policy_documents "
                 "WHERE policy_id = %s ORDER BY document", (pid,))
    if docs:
        p["documents"] = [d["document"] for d in docs]
    return p


_POLICY_COLS = ("policy_id, lob, product_id, product_name, customer_id, "
                "status, TO_CHAR(start_date, 'YYYY-MM-DD') AS start_date, "
                "TO_CHAR(end_date, 'YYYY-MM-DD') AS end_date, "
                "TO_CHAR(renewed_to, 'YYYY-MM-DD') AS renewed_to, "
                "sum_insured, idv, ncb_pct")


def policy(policy_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._POLICIES.get(policy_id)
    row = _one(f"SELECT {_POLICY_COLS} FROM mcb.policies WHERE policy_id = %s",
               (policy_id,))
    return _hydrate_policy(row) if row else None


def policies_for(customer_id: str, lob: str) -> list[dict]:
    if not using_redshift():
        from app.coremock import store

        return [p for p in store._POLICIES.values()
                if p["customer_id"] == customer_id and p["lob"] == lob]
    rows = _rows(f"SELECT {_POLICY_COLS} FROM mcb.policies "
                 "WHERE customer_id = %s AND lob = %s ORDER BY policy_id",
                 (customer_id, lob))
    return [_hydrate_policy(r) for r in rows]


def vehicle(registration: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._VEHICLES.get(registration)
    row = _one("SELECT registration, make, model, variant, year, fuel, cc, "
               "vehicle_class, rto, prior_insurer, prior_ncb_pct, "
               "TO_CHAR(prior_expiry, 'YYYY-MM-DD') AS prior_expiry "
               "FROM mcb.vehicles WHERE registration = %s", (registration,))
    return _clean(row) if row else None


def network(kind: str) -> list[dict]:
    if not using_redshift():
        from app.coremock import store

        return list(store._NETWORK.get(kind, []))
    rows = _rows("SELECT name, city, pincode, cashless, km FROM mcb.network "
                 "WHERE kind = %s ORDER BY km", (kind,))
    out = []
    for r in rows:
        r = _clean(r)
        r["km"] = float(r["km"]) if r.get("km") is not None else None
        sp = _rows("SELECT specialty FROM mcb.network_specialties "
                   "WHERE name = %s ORDER BY specialty", (r["name"],))
        if sp:
            r["specialties"] = [s["specialty"] for s in sp]
        out.append(r)
    return out


# ---------------------------------------------------------------------------
# writes
# ---------------------------------------------------------------------------
def put_policy(p: dict) -> None:
    """A newly issued policy. Delete-then-insert: Redshift has no upsert."""
    if not using_redshift():
        from app.coremock import store

        store._POLICIES[p["policy_id"]] = p
        return
    pid = p["policy_id"]
    for t in ("policies", "policy_members", "policy_vehicles",
              "policy_documents"):
        _exec(f"DELETE FROM mcb.{t} WHERE policy_id = %s", (pid,))
    _exec("INSERT INTO mcb.policies (policy_id, lob, product_id, "
          "product_name, customer_id, status, start_date, end_date, "
          "renewed_to, sum_insured, idv, ncb_pct) "
          "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
          (pid, p.get("lob"), p.get("product_id"), p.get("product_name"),
           p.get("customer_id"), p.get("status"), p.get("start_date"),
           p.get("end_date"), p.get("renewed_to"), p.get("sum_insured"),
           p.get("idv"), p.get("ncb_pct")))
    for m in p.get("members") or []:
        _exec("INSERT INTO mcb.policy_members (policy_id, member_id, name, "
              "age, relation) VALUES (%s,%s,%s,%s,%s)",
              (pid, m.get("member_id"), m.get("name"), m.get("age"),
               m.get("relation")))
    v = p.get("vehicle")
    if v:
        _exec("INSERT INTO mcb.policy_vehicles (policy_id, registration, "
              "make, model, variant, year, fuel, rto) "
              "VALUES (%s,%s,%s,%s,%s,%s,%s,%s)",
              (pid, v.get("registration"), v.get("make"), v.get("model"),
               v.get("variant"), v.get("year"), v.get("fuel"), v.get("rto")))
    for d in p.get("documents") or []:
        _exec("INSERT INTO mcb.policy_documents (policy_id, document) "
              "VALUES (%s,%s)", (pid, d))


def _doc_put(table: str, key_col: str, key: str, cols: dict,
             body: dict) -> None:
    names = ", ".join([key_col, *cols.keys(), "body"])
    marks = ", ".join(["%s"] * (len(cols) + 2))
    _exec(f"DELETE FROM mcb.{table} WHERE {key_col} = %s", (key,))
    _exec(f"INSERT INTO mcb.{table} ({names}) VALUES ({marks})",
          (key, *cols.values(), json.dumps(body, default=str)))


def _doc_get(table: str, key_col: str, key: str) -> dict | None:
    row = _one(f"SELECT body FROM mcb.{table} WHERE {key_col} = %s", (key,))
    return json.loads(row["body"]) if row and row.get("body") else None


def put_quote(qd: dict) -> None:
    if not using_redshift():
        from app.coremock import store

        store._QUOTES[qd["quote_id"]] = qd
        return
    _doc_put("quotes", "quote_id", qd["quote_id"],
             {"lob": qd.get("lob"), "customer_id": qd.get("customer_id")}, qd)


def get_quote(quote_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._QUOTES.get(quote_id)
    return _doc_get("quotes", "quote_id", quote_id)


def put_application(app: dict) -> None:
    if not using_redshift():
        from app.coremock import store

        store._APPLICATIONS[app["application_id"]] = app
        return
    _doc_put("applications", "application_id", app["application_id"],
             {"quote_id": app.get("quote_id"),
              "customer_id": app.get("customer_id"),
              "lob": app.get("lob"), "status": app.get("status")}, app)


def get_application(application_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._APPLICATIONS.get(application_id)
    return _doc_get("applications", "application_id", application_id)


def put_claim(c: dict) -> None:
    if not using_redshift():
        from app.coremock import store

        store._CLAIMS[c["claim_id"]] = c
        return
    _doc_put("claims", "claim_id", c["claim_id"],
             {"policy_id": c.get("policy_id"), "lob": c.get("lob"),
              "status": c.get("status")}, c)


def get_claim(claim_id: str) -> dict | None:
    if not using_redshift():
        from app.coremock import store

        return store._CLAIMS.get(claim_id)
    return _doc_get("claims", "claim_id", claim_id)


# ---------------------------------------------------------------------------
# idempotency (AG-6 / CO-1)
# ---------------------------------------------------------------------------
def ledger_get(key: str) -> dict | None:
    """The recorded outcome of a write that already happened, or None.

    The digest check that decides whether a replayed key carries the SAME
    payload stays in store.py. This only stores and returns; it does not know
    what makes a replay legitimate.
    """
    if not using_redshift():
        from app.coremock import store

        return store._IDEMPOTENCY.get(key)
    row = _one("SELECT result_json FROM mcb.write_ledger "
               "WHERE idempotency_key = %s", (key,))
    return json.loads(row["result_json"]) if row and row.get("result_json") else None


def ledger_put(key: str, op: str, record: dict) -> dict:
    """Record a write, and return what the ledger holds afterwards.

    Redshift enforces no unique constraint and has no `ON CONFLICT`, so the
    insert is guarded by `WHERE NOT EXISTS` and then READ BACK. The read-back
    is the point: if a concurrent caller won, their result is the one both
    must return, or a retried payment_collect would report two different
    receipts for one payment.

    Worth being precise about the guarantee. Two exactly simultaneous callers
    could both see no row and both attempt the insert; the guard makes the
    second a no-op and the read-back makes them agree. Sequential retries -
    which is what a channel actually produces - are exact.
    """
    if not using_redshift():
        from app.coremock import store

        store._IDEMPOTENCY[key] = record
        return record
    _exec("INSERT INTO mcb.write_ledger (idempotency_key, tool_name, "
          "user_id, result_json) SELECT %s, %s, %s, %s WHERE NOT EXISTS "
          "(SELECT 1 FROM mcb.write_ledger WHERE idempotency_key = %s)",
          (key, op, "", json.dumps(record, default=str), key))
    return ledger_get(key) or record


def reset_connection() -> None:
    c = getattr(_LOCAL, "conn", None)
    if c is not None:
        try:
            c.close()
        except Exception:                                    # noqa: BLE001
            pass
    _LOCAL.conn = None
