"""Generate the Redshift schema and seed from the fixtures already in code.

`app/coremock/store.py` holds the reference data as Python dicts. Writing a
second copy of it in SQL would mean two sources of truth that drift, and the
first symptom of the drift would be an answer that is right offline and wrong
in production. So the SQL is generated.

Reference data gets REAL columns - customers, producers, policies, members,
vehicles, network - because build requirement 1 asks for a database populated
with proper data, and a JSON blob in one column is not that.

Transactional state - quotes, applications, claims - is genuinely
document-shaped: an application carries a set of gates whose composition
differs by line of business, and a quote carries a premium breakup that does
the same. Those keep a typed envelope (ids, owner, status, timestamps) with
the body as JSON, which is honest about what they are rather than pretending
to a schema that would need altering per product.

    uv run python scripts/gen_seed_sql.py
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.coremock import store  # noqa: E402

OUT = (pathlib.Path(__file__).resolve().parents[1]
       / "infra" / "data" / "migrate" / "migrations" / "002_reference.sql")


def q(v) -> str:
    """One SQL literal. Redshift has no parameter binding in a .sql file."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def j(v) -> str:
    return q(json.dumps(v, ensure_ascii=False, separators=(",", ":")))


SCHEMA = """
-- 002_reference - the core store, as a real schema.
--
-- GENERATED by scripts/gen_seed_sql.py from app/coremock/store.py. Do not
-- edit by hand: the fixtures in Python are the source of truth, and a hand
-- edit here would drift from what the offline tests assert.
--
-- Redshift notes that shaped this:
--   * PRIMARY KEY and UNIQUE are recorded but NOT enforced. Uniqueness is
--     the application's job - see mcb.write_ledger and the MERGE pattern.
--   * DISTSTYLE ALL suits every table here; the whole dataset is kilobytes.
--   * No ON CONFLICT. Seeding therefore DELETEs then INSERTs, which also
--     makes this migration safe to re-run.

CREATE SCHEMA IF NOT EXISTS mcb;

CREATE TABLE IF NOT EXISTS mcb.customers (
    user_id      VARCHAR(64)  NOT NULL,
    customer_id  VARCHAR(32)  NOT NULL,
    name         VARCHAR(128),
    city         VARCHAR(64),
    pincode      VARCHAR(12),
    kyc_status   VARCHAR(24)
) DISTSTYLE ALL SORTKEY (user_id);

CREATE TABLE IF NOT EXISTS mcb.producers (
    user_id            VARCHAR(64) NOT NULL,
    producer_id        VARCHAR(32) NOT NULL,
    name               VARCHAR(128),
    licence            VARCHAR(64),
    branch             VARCHAR(64),
    licence_valid_to   DATE
) DISTSTYLE ALL SORTKEY (user_id);

CREATE TABLE IF NOT EXISTS mcb.policies (
    policy_id     VARCHAR(32) NOT NULL,
    lob           VARCHAR(16) NOT NULL,
    product_id    VARCHAR(16),
    product_name  VARCHAR(128),
    customer_id   VARCHAR(32) NOT NULL,
    status        VARCHAR(24),
    start_date    DATE,
    end_date      DATE,
    renewed_to    DATE,
    sum_insured   BIGINT,
    idv           BIGINT,
    ncb_pct       INTEGER
) DISTSTYLE ALL SORTKEY (customer_id, lob);

CREATE TABLE IF NOT EXISTS mcb.policy_members (
    policy_id  VARCHAR(32) NOT NULL,
    member_id  VARCHAR(16) NOT NULL,
    name       VARCHAR(128),
    age        INTEGER,
    relation   VARCHAR(32)
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.policy_vehicles (
    policy_id     VARCHAR(32) NOT NULL,
    registration  VARCHAR(24),
    make          VARCHAR(48),
    model         VARCHAR(48),
    variant       VARCHAR(48),
    year          INTEGER,
    fuel          VARCHAR(24),
    rto           VARCHAR(48)
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.policy_documents (
    policy_id  VARCHAR(32) NOT NULL,
    document   VARCHAR(64) NOT NULL
) DISTSTYLE ALL SORTKEY (policy_id);

CREATE TABLE IF NOT EXISTS mcb.vehicles (
    registration    VARCHAR(24) NOT NULL,
    make            VARCHAR(48),
    model           VARCHAR(48),
    variant         VARCHAR(48),
    year            INTEGER,
    fuel            VARCHAR(24),
    cc              INTEGER,
    vehicle_class   VARCHAR(32),
    rto             VARCHAR(48),
    prior_insurer   VARCHAR(48),
    prior_ncb_pct   INTEGER,
    prior_expiry    DATE
) DISTSTYLE ALL SORTKEY (registration);

CREATE TABLE IF NOT EXISTS mcb.network (
    kind      VARCHAR(16) NOT NULL,   -- hospital | garage
    name      VARCHAR(128) NOT NULL,
    city      VARCHAR(64),
    pincode   VARCHAR(12),
    cashless  BOOLEAN,
    km        DECIMAL(6,2)
) DISTSTYLE ALL SORTKEY (kind, pincode);

CREATE TABLE IF NOT EXISTS mcb.network_specialties (
    name       VARCHAR(128) NOT NULL,
    specialty  VARCHAR(48)  NOT NULL
) DISTSTYLE ALL SORTKEY (name);

-- Transactional state. Typed envelope, JSON body - see the module docstring
-- for why these are not fully columnar.
CREATE TABLE IF NOT EXISTS mcb.quotes (
    quote_id     VARCHAR(48) NOT NULL,
    lob          VARCHAR(16),
    customer_id  VARCHAR(32),
    created_at   TIMESTAMP DEFAULT SYSDATE,
    body         VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (quote_id);

CREATE TABLE IF NOT EXISTS mcb.applications (
    application_id  VARCHAR(48) NOT NULL,
    quote_id        VARCHAR(48),
    customer_id     VARCHAR(32),
    lob             VARCHAR(16),
    status          VARCHAR(32),
    updated_at      TIMESTAMP DEFAULT SYSDATE,
    body            VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (application_id);

CREATE TABLE IF NOT EXISTS mcb.claims (
    claim_id     VARCHAR(48) NOT NULL,
    policy_id    VARCHAR(32),
    lob          VARCHAR(16),
    status       VARCHAR(32),
    updated_at   TIMESTAMP DEFAULT SYSDATE,
    body         VARCHAR(65535)
) DISTSTYLE ALL SORTKEY (claim_id);
"""


def seed() -> list[str]:
    out: list[str] = []
    add = out.append

    # Re-runnable: clear then load. Redshift has no upsert to lean on.
    for t in ("customers", "producers", "policies", "policy_members",
              "policy_vehicles", "policy_documents", "vehicles",
              "network", "network_specialties"):
        add(f"DELETE FROM mcb.{t}")

    for user_id, c in store._CUSTOMERS.items():
        add("INSERT INTO mcb.customers "
            "(user_id, customer_id, name, city, pincode, kyc_status) VALUES ("
            f"{q(user_id)}, {q(c['customer_id'])}, {q(c.get('name'))}, "
            f"{q(c.get('city'))}, {q(c.get('pincode'))}, {q(c.get('kyc_status'))})")

    for user_id, p in store._PRODUCERS.items():
        add("INSERT INTO mcb.producers "
            "(user_id, producer_id, name, licence, branch, licence_valid_to) "
            f"VALUES ({q(user_id)}, {q(p['producer_id'])}, {q(p.get('name'))}, "
            f"{q(p.get('licence'))}, {q(p.get('branch'))}, "
            f"{q(p.get('licence_valid_to'))})")

    for pid, p in store._POLICIES.items():
        add("INSERT INTO mcb.policies (policy_id, lob, product_id, "
            "product_name, customer_id, status, start_date, end_date, "
            "renewed_to, sum_insured, idv, ncb_pct) VALUES ("
            f"{q(pid)}, {q(p.get('lob'))}, {q(p.get('product_id'))}, "
            f"{q(p.get('product_name'))}, {q(p.get('customer_id'))}, "
            f"{q(p.get('status'))}, {q(p.get('start_date'))}, "
            f"{q(p.get('end_date'))}, {q(p.get('renewed_to'))}, "
            f"{q(p.get('sum_insured'))}, {q(p.get('idv'))}, {q(p.get('ncb_pct'))})")
        for m in p.get("members") or []:
            add("INSERT INTO mcb.policy_members "
                "(policy_id, member_id, name, age, relation) VALUES ("
                f"{q(pid)}, {q(m.get('member_id'))}, {q(m.get('name'))}, "
                f"{q(m.get('age'))}, {q(m.get('relation'))})")
        v = p.get("vehicle")
        if v:
            add("INSERT INTO mcb.policy_vehicles (policy_id, registration, "
                "make, model, variant, year, fuel, rto) VALUES ("
                f"{q(pid)}, {q(v.get('registration'))}, {q(v.get('make'))}, "
                f"{q(v.get('model'))}, {q(v.get('variant'))}, {q(v.get('year'))}, "
                f"{q(v.get('fuel'))}, {q(v.get('rto'))})")
        for d in p.get("documents") or []:
            add(f"INSERT INTO mcb.policy_documents (policy_id, document) "
                f"VALUES ({q(pid)}, {q(d)})")

    for reg, v in store._VEHICLES.items():
        add("INSERT INTO mcb.vehicles (registration, make, model, variant, "
            "year, fuel, cc, vehicle_class, rto, prior_insurer, "
            "prior_ncb_pct, prior_expiry) VALUES ("
            f"{q(reg)}, {q(v.get('make'))}, {q(v.get('model'))}, "
            f"{q(v.get('variant'))}, {q(v.get('year'))}, {q(v.get('fuel'))}, "
            f"{q(v.get('cc'))}, {q(v.get('vehicle_class'))}, {q(v.get('rto'))}, "
            f"{q(v.get('prior_insurer'))}, {q(v.get('prior_ncb_pct'))}, "
            f"{q(v.get('prior_expiry'))})")

    for kind, rows in store._NETWORK.items():
        for r in rows:
            add("INSERT INTO mcb.network (kind, name, city, pincode, "
                "cashless, km) VALUES ("
                f"{q(kind)}, {q(r.get('name'))}, {q(r.get('city'))}, "
                f"{q(r.get('pincode'))}, {q(r.get('cashless'))}, {q(r.get('km'))})")
            for sp in r.get("specialties") or []:
                add("INSERT INTO mcb.network_specialties (name, specialty) "
                    f"VALUES ({q(r.get('name'))}, {q(sp)})")
    return out


def main() -> int:
    statements = [s.strip() for s in SCHEMA.split(";") if s.strip()]
    body = SCHEMA.rstrip().rstrip(";") + ";\n\n-- ---- seed ----\n"
    body += ";\n".join(seed()) + ";\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"{OUT.name}: {len(statements)} DDL + {len(seed())} DML statements, "
          f"{OUT.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
